# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'
  imageName: 'srinath-chandra/trivycontainerscandemo'
  trivyVersion: 0.17.1

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/ACRTasks/dockerfile'
        repository: '$(imageName)'
        tags: '$(tag)'
    - task: CmdLine@2
      displayName: List Docker Images
      inputs:
        script: |
         docker images
    - task: CmdLine@2
      displayName: Scan
      inputs:
        script: |
         docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 0 --severity LOW,MEDIUM,HIGH,CRITICAL --ignore-unfixed $(imageName):$(tag)
         
         #docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 1 --severity CRITICAL --ignore-unfixed $(imageName):$(tag)
    - task: CmdLine@2
      displayName: "Download and Run trivy scan"
      inputs:
        script: |
            sudo apt-get install rpm
            wget https://github.com/aquasecurity/trivy/releases/download/v$(trivyVersion)/trivy_$(trivyVersion)_Linux-64bit.deb
            sudo dpkg -i trivy_$(trivyVersion)_Linux-64bit.deb
            trivy -v
            trivy image --quiet --severity LOW,MEDIUM,HIGH,CRITICAL $(imageName):$(tag)         
