trigger:
- master

parameters:
- name: file_name
  type: string
  default: ''
  values:
    - TestFile.txt

pool:
  vmImage: ubuntu-latest
steps:
- task: DownloadSecureFile@1
  displayName: Download Secure File 
  name: secureFileDownload
  inputs:
    secureFile: '${{ parameters.file_name }}'
- task: CmdLine@2
    displayName: Display file
    inputs:
      script: |
        cat TestFile.txt
