# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildNumber)'
  imageName: 'srinath-chandra/TrivyContainerScanDemo'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/ACRTasks/dockerfile'
        repository: '$(imageName)'
        tags: '$(tag)'
    - task: CmdLine@2
      displayName: List Docker Images
      inputs:
        script: |
         docker images