# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadSecureFile@1
      displayName: Download Secure File
      inputs:
        secureFile: 'TestFile.txt'
    - task: CmdLine@2
      displayName: Display file
      inputs:
        script: |
          cat /home/vsts/work/_temp/TestFile.txt
